### ISSUE TITLE
WebSphere Liberty: SRVE0216E

### ISSUE THREAD

**Issue by vpiotr** [rgielen/struts1filter#3]
Installing this filter on WebSphere Liberty (WebSphere Application Server 8.5.5.5) with Struts causes the following error: SRVE0216E

	java.io.IOException: SRVE0216E: post body contains less bytes than specified by content-length
		at com.ibm.ws.webcontainer.servlet.RequestUtils.getPostBody(RequestUtils.java:312)
		at com.ibm.ws.webcontainer.servlet.RequestUtils.parsePostData(RequestUtils.java:358)
		at com.ibm.ws.webcontainer.srt.SRTServletRequest.parsePostData(SRTServletRequest.java:2410)
		at com.ibm.ws.webcontainer.srt.SRTServletRequest.parseParameters(SRTServletRequest.java:2287)
		at com.ibm.ws.webcontainer.srt.SRTServletRequest.getParameterNames(SRTServletRequest.java:1879)
		at javax.servlet.ServletRequestWrapper.getParameterNames(ServletRequestWrapper.java:157)
		at net.rgielen.struts1.filter.ParamWrapperFilter$ParamFilteredRequest.getParameterNames(ParamWrapperFilter.java:143)
		at org.apache.struts.util.RequestUtils.populate(RequestUtils.java:431)
		at org.apache.struts.chain.commands.servlet.PopulateActionForm.populate(PopulateActionForm.java:50)
		at org.apache.struts.chain.commands.AbstractPopulateActionForm.execute(AbstractPopulateActionForm.java:60)
		at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
		at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
		at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:305)
		at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
		at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
		at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
		at org.apache.struts.action.ActionServlet.doPost(ActionServlet.java:462)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
		at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1285)
		at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:776)
		at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:473)
		at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:135)
		at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:89)
		at net.rgielen.struts1.filter.ParamWrapperFilter.doFilter(ParamWrapperFilter.java:79)
		at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:206)
		at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:86)
		at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:978)
		at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1100)
		at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4845)
		at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:297)
		at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:981)
		at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:262)
		at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:955)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
		at java.lang.Thread.run(Thread.java:745)

Fixing it by adding the following in server.xml does not help:

    <webContainer enableMultiReadOfPostData="true"/>

Probably because of this limitation:
[In WebSphere Liberty Profile enableMultiReadOfPostData Is Not Available ](https://www.ibm.com/developerworks/community/blogs/18d10b14-e2c8-4780-bace-9af1fc463cc0/entry/in_websphere_liberty_profile_enablemultireadofpostdata_is_not_available?lang=en)

**Comment by vpiotr** [comment]
Workaround: use patched struts distribution instead of this filter.
Patch link: https://github.com/apache/struts1/pull/1/files
Patched struts 1.3.10 is available for example for Fedora 20 in build "struts-1.3.10-10.fc20" in form of RPM:
http://koji.fedoraproject.org/koji/buildinfo?buildID=552377

**Comment by pwntester** [comment]
Cool, didnt know that patch made it to any official release

**Comment by pwntester** [comment]
Filter resets the content length to 0 in case it finds an offensive parameter, so this may be something webSphere specific that we may not be able to fix. In addition, the Struts 2 patch its a much better solution so if you can get a distro with it included or compile it yourself, that will be a better solution.

**Comment by vpiotr** [comment]
Just to be clear: this error appears during standard application processing when there is no offensive parameter. 

So my suggestion (without filter processing understanding): if possible, skip stream re-loading when there is no offensive parameter.
